version: '3.1'

services:
  
  postgresql:
    image: postgres:14
    restart: always
    container_name: postgresql14
    environment:
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./scripts/database/startup.sh:/docker-entrypoint-initdb.d/startup.sh
      - ./scripts/database/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "jupyter"
    volumes:
      - /home/cvale/Projects/quetzalbet/notebooks:/home/jovyan/work
  openldap:
    image: bitnami/openldap:2
    container_name: openldap2
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_ADMIN_USERNAME=Administrator
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_ROOT=dc=trt12,dc=gov,dc=br
    volumes:
      - openldap-data:/bitnami/openldap
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    container_name: keycloak1204
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: jFRGxxWbOcMDd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: P4ssw0rd
    ports:
      - 8080:8080
    depends_on:
      - postgresql
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: m0ng0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=m4r14db

volumes:
  postgresql-data:
    driver: local
  mongodb-data:
    driver: local
  openldap-data:
    driver: local
  mariadb-data:
    driver: local
