CREATE USER veritas WITH LOGIN PASSWORD 'jFRGxxWbOcMDd';
CREATE DATABASE veritas_desenv WITH OWNER veritas;
CREATE USER keycloak WITH LOGIN PASSWORD 'jFRGxxWbOcMDd';
CREATE DATABASE keycloak WITH OWNER keycloak;
